#index:
#    path: /
#    controller: App\Controller\DefaultController::index

notification_page:
    path: /frontend-homework/1
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'notifications.html.twig'
